version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - menui-network
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    networks:
      - menui-network
    restart: unless-stopped

  laravel:
    build: 
      context: ./laravel-app
      dockerfile: Dockerfile.prod
    volumes:
      - ./storage:/var/www/html/storage
    depends_on:
      - db
      - redis
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=db
      - REDIS_HOST=redis
      - AI_SERVICE_URL=http://ai-service:8000
    networks:
      - menui-network
    restart: unless-stopped

  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile.prod
    volumes:
      - ./storage:/app/storage
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 2
    networks:
      - menui-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf
      - ./deploy/ssl:/etc/nginx/ssl
    depends_on:
      - laravel
    networks:
      - menui-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  menui-network:
    driver: bridge